# Data exploration:-

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn.linear_model import LinearRegression
from google.colab import drive
drive.mount('/content/drive')
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score

data = pd.read_csv('/content/drive/MyDrive/Dataset/Supply_Chain_Dataset_New.csv', encoding='latin1', engine='python')

data.info()

Mounted at /content/drive
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 48 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   Type                           180519 non-null  object 
 1   Days for shipping (real)       180519 non-null  int64  
 2   Days for shipment (scheduled)  180519 non-null  int64  
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object 
 6   Late_delivery_risk             180519 non-null  int64  
 7   Category Id                    180519 non-null  int64  
 8   Category Name                  180519 non-null  object 
 9   Customer City                  180519 non-null  object 
 10  Customer Country               180519 non-null  object 
 11  Customer Email                 180519 non-null  object 
 12  Cust

# Pre process:-

In [2]:
#drop unwanted columns
unwanted_columns =["Category Id","Customer Email","Customer Zipcode","Customer Street","Customer Fname","Customer Id","Customer Lname","Customer Segment","Latitude","Longitude","Order Customer Id","order date (DateOrders)","Order Id","Order Item Cardprod Id","Order Item Id","Order Zipcode","Product Card Id","Product Category Id","Product Status","shipping date (DateOrders)"]
data.drop(unwanted_columns, axis=1, inplace=True)

# change object data into int or float

hist_data = data.copy(deep=False)

from sklearn.preprocessing import LabelEncoder
def Change_obj_type(data):
    for column in data.columns:
        if data[column].dtype == type(object):
            le = LabelEncoder()
            data[column] = le.fit_transform(data[column])
    return data
new_data = Change_obj_type(hist_data)
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 28 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   Type                           180519 non-null  int64  
 1   Days for shipping (real)       180519 non-null  int64  
 2   Days for shipment (scheduled)  180519 non-null  int64  
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  int64  
 6   Late_delivery_risk             180519 non-null  int64  
 7   Category Name                  180519 non-null  int64  
 8   Customer City                  180519 non-null  int64  
 9   Customer Country               180519 non-null  int64  
 10  Customer State                 180519 non-null  int64  
 11  Market                         180519 non-null  int64  
 12  Order City                    

# Model build:

**1.Random Forest Classifier**

In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Load your dataset
# Assuming your DataFrame is named 'new_data'
X = new_data[['Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer',
               'Order Item Discount', 'Order Item Discount Rate', 'Order Item Product Price', 'Order Item Profit Ratio',
               'Order Item Quantity', 'Order Status','Sales', 'Order Item Total', 'Order Profit Per Order', 'Product Price']]
y = new_data['Delivery Status']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features (important for PCA)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Apply PCA for feature selection with 3 components
pca = PCA(n_components=4)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

# Create a Random Forest classifier
rf_model = RandomForestClassifier(random_state=42, n_estimators=100)

# Train the model on the PCA-transformed data
rf_model.fit(X_train_pca, y_train)

# Make predictions on the test set
y_pred_rf_pca = rf_model.predict(X_test_pca)

# Evaluate the Random Forest model with PCA
accuracy_rf_pca = accuracy_score(y_test, y_pred_rf_pca)
conf_matrix_rf_pca = confusion_matrix(y_test, y_pred_rf_pca)
classification_rep_rf_pca = classification_report(y_test, y_pred_rf_pca)

# Print the results with PCA
print(f'Random Forest Accuracy with PCA: {accuracy_rf_pca}')
print(f'Random Forest Confusion Matrix with PCA:\n{conf_matrix_rf_pca}')
print(f'Random Forest Classification Report with PCA:\n{classification_rep_rf_pca}')


Random Forest Accuracy with PCA: 0.9612508309328607
Random Forest Confusion Matrix with PCA:
[[ 8313     5     2     0]
 [    4 19701     6     1]
 [  303   780   195   292]
 [    0     0     6  6496]]
Random Forest Classification Report with PCA:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98      8320
           1       0.96      1.00      0.98     19712
           2       0.93      0.12      0.22      1570
           3       0.96      1.00      0.98      6502

    accuracy                           0.96     36104
   macro avg       0.95      0.78      0.79     36104
weighted avg       0.96      0.96      0.95     36104



suitable for bi.